select
  MA.ID
  MA.EINTRITTSDATUM as ZAHLPFLICHT_VON,
  coalesce(MA.AUSTRITTSDATUM, CURRENT_DATE) as ZAHLPFLICHT_BIS,
  B.NAME as BEITRAG_NAME,
  B.BEITRAG
from
  TC_MITGLIED MA
join
  TC_DATUM D on D.DATE between MA.EINTRITTSDATUM and coalesce(MA.AUSTRITTSDATUM, CURRENT_DATE)
join
  TC_MITGLIED MH on D.DATE between MH.GUELTIG_VON and MH.GUELTIG_BIS
join
  TC_BEITRAG B on B.NHID = MH.BEITRAG_NHID and D.DATE between B.GUELTIG_VON and B.GUELTIG_BIS
where
  CURRENT_DATE between MA.GUELTIG_VON and MA.GUELTIG_BIS and
  D.DAY = 1 and
;
