select
  T1.ID,
  T1.NHID,
  T1.GUELTIG_VON,
  T1.GUELTIG_BIS,
  T2.ID,
  T2.NHID,
  T2.GUELTIG_VON,
  T2.GUELTIG_BIS
from
  TC_BEITRAG as T1,
  TC_BEITRAG as T2
where
  T1.ID   != T2.ID   and
  T1.NHID  = T2.NHID and
  (
    T1.GUELTIG_VON between T2.GUELTIG_VON and T2.GUELTIG_BIS or
    T1.GUELTIG_BIS between T2.GUELTIG_VON and T2.GUELTIG_BIS
  )